Update localization.ru.lua
DeadlyBossMods/DBM-Unified pull request #246
Opened 2023-07-18 22:42 UTC by Hollicsh

2023-07-19 05:14 UTC, MysticalOS commented
This is probably out of date already so won't merge it yet til synced with latest.

2023-07-19 05:15 UTC, MysticalOS requested changes
Needs updated text from newer english commit

2023-07-19 10:44 UTC, Hollicsh commented
Yep. Ready.

2023-07-25 06:50 UTC, MysticalOS approved these changes

2023-07-25 06:50 UTC, merged